### ISSUE TITLE
如何将chat-tts的.pt音色文件转换到AI-Forge呢？

### ISSUE THREAD

**Issue by pengyrDL** [lenML/Speech-AI-Forge-spks#1]
目前Forge可供下载的预挑选音色还是太少了

**Comment by zhzLuke96** [comment]
直接把 .pt 转spk文件的脚本目前还没有，稍等我看看可以添加一个简单的脚本

顺带一提，chattts官方webui里有一个音色编码为字符串的功能，那个功能生成的`code`（就是看起来类似乱码那个），目前有一个脚本可以用来将其转为 spkv1.json 文件

可以看这里：
https://github.com/lenML/Speech-AI-Forge/blob/0b31b2238d994d07f54723f4f2dce4afb0fcdc44/scripts/spk/code_to_spk.py#L39-L44
用法就是在项目目录下执行 `python -m scripts.spk.code_to_spk --code "这里填你的code" --out "test.spkv1.json"`

增加这个脚本的原因，可以看这个讨论：
https://github.com/lenML/Speech-AI-Forge/discussions/128

**Comment by zhzLuke96** [comment]
added https://github.com/lenML/Speech-AI-Forge/commit/1bf4c1a6df99c5b822a8265d309f1056d860f5c0

主库中已添加脚本：
https://github.com/lenML/Speech-AI-Forge/blob/main/scripts/spk/chattts_pt_to_spk.py

这个脚本生成的 spk 文件除了音色以外都是空的（可自行修改json），且只适用于 chattts 模型的 pt 文件

**Comment by pengyrDL** [comment]
非常感谢你的工作！
